config: {}
networks:
- config:
    ipv4.address: auto
    ipv4.nat: "true"
    ipv6.address: none
  name: lxdbr0
  type: bridge
storage_pools:
- config:
    size: 20GB
  name: default
  driver: btrfs
profiles:
- config:
    security.nesting: "true"
  name: default
  devices:
    eth0:
      name: eth0
      network: lxdbr0
      type: nic
    root:
      path: /
      pool: default
      type: disk
